---
# Dotfiles
dotfiles_symlinks:
  - config/git
  - config/jupyter
  - local/share/bin/git-status
  - gradle
  - tmux.conf
  - vimrc
  - zprofile
  - zshenv
  - zshrc

# Homebrew
homebrew_prefix: "{{ ansible_env.HOME }}"
homebrew_install_path: "{{ homebrew_prefix }}/.homebrew"
homebrew_brew_bin_path: "{{ homebrew_install_path }}/bin"
homebrew_prefix_owner: "{{ ansible_user_id }}"

homebrew_taps:
  - caskroom/versions
  - caskroom/fonts
  - homebrew/services
  - damselem/repo

homebrew_installed_packages:
  - awscli
  - bazaar
  - chromedriver
  - coreutils
  - docker
  - docker-compose
  - go
  - gpg2
  - gradle
  - jdt-language-server
  - maven
  - mercurial
  - nmap
  - pyenv
  - reattach-to-user-namespace
  - sqlite
  - sshfs
  - tldr
  - tmux
  - tree
  - upx
  - vim
  - zlib

homebrew_cask_apps:
  - 1password
  - caffeine
  - docker
  - firefox
  - flux
  - google-cloud-sdk
  - gpg-suite
  - intellij-idea
  - java
  - java8
  - osxfuse
  - rowanj-gitx
  - sizeup
  - telegram
  - the-unarchiver
  - visual-studio-code
  - vlc
  - whatsapp

zsh_completions_dir: "{{ homebrew_path }}/share/zsh-completions"
