---
# Dotfiles
dotfiles_symlinks:
  - config/alacritty
  - git
  - gitconfig
  - gradle
  - jupyter
  - tmux.conf
  - vimrc
  - zprofile
  - zshenv
  - zshrc

# Homebrew
homebrew_prefix: "{{ ansible_env.HOME }}"
homebrew_install_path: "{{ homebrew_prefix }}/.homebrew"
homebrew_brew_bin_path: "{{ homebrew_install_path }}/bin"
homebrew_prefix_owner: "{{ ansible_user_id }}"

homebrew_taps:
  - caskroom/versions
  - caskroom/fonts
  - homebrew/fuse
  - homebrew/science
  - homebrew/services
  - damselem/repo

homebrew_installed_packages:
  - awscli
  - bazaar
  - chromedriver
  - coreutils
  - docker
  - docker-compose
  - go
  - gpg2
  - gradle
  - jdt-language-server
  - jenv
  - maven
  - mercurial
  - nmap
  - pyenv
  - rclone
  - reattach-to-user-namespace
  - rustup-init
  - sqlite
  - sshfs
  - terraform
  - tldr
  - tmux
  - tree
  - upx
  - vim
  - zlib
  - zplug

homebrew_cask_apps:
  - 1password
  - caffeine
  - docker
  - firefox
  - flux
  - font-dejavu-sans
  - google-cloud-sdk
  - gpg-suite
  - intellij-idea
  - java
  - osxfuse
  - rowanj-gitx
  - sizeup
  - telegram
  - the-unarchiver
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - whatsapp
