---
- name: Mac OS X Ansible play
  hosts: damselem-macbookpro
  pre_tasks:
    - include_tasks: "tasks/pre/{{ ansible_hostname }}.yml"
  roles:
    - ansible-role-homebrew
    - ansible-role-sshconfig
    - role: dotfiles
      homebrew_path: "{{ homebrew_install_path }}"
      homebrew_bin_path: "{{ homebrew_brew_bin_path }}"
