---
- name: Mac OS X Ansible play
  hosts: damselem-macbookpro

  roles:
    - role: ansible-role-hosts
    - role: ansible-role-homebrew
    - role: ansible-role-sshconfig
    - role: ansible-role-rust
    - role: ansible-role-dotfiles
      homebrew_path: "{{ homebrew_install_path }}"
      homebrew_bin_path: "{{ homebrew_brew_bin_path }}"
