---
- name: macOS standard play
  hosts: macos

  roles:
    - role: ansible-role-hosts
    # - role: ansible-role-homebrew
    - role: ansible-role-sshconfig
    - role: ansible-role-dotfiles
    - role: cmprescott.autofs_ng
      become: True
      autofs_indirect_maps:
        - name: "autofs.nas"
          path: "{{ nfs_mount_root }}"
          mounts:
            - name: "{{ nfs_mount_root_dir }}"
              fstype: "nfs,rw,insecure,all_squash"
              url: "{{ nas_host }}:/volume1/media"


- name: macOS NAS play
  hosts: macos-server