---
# Ansible
ansible_host: localhost
ansible_connection: local
ansible_user: damselem

# Homebrew
homebrew_prefix_group: primarygroup
homebrew_install_path_group: primarygroup
homebrew_brew_bin_path_group: primarygroup

# SSH
ssh_config_group: primarygroup